version: '3.9'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6390:6379
    volumes:
      - ~/apps/ds-prototype/redis/data:/root/redis
      - ~/apps/ds-prototype/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6390
      - REDIS_DATABASES=1

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5682:5672
      - 15682:15672
    volumes:
      - ~/apps/ds-prototype/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/apps/ds-prototype/rabbitmq/log/:/var/log/rabbitmq/
    networks:
      - rabbitmq_go_net_2

  nginx:
    image: nginx:latest
    ports:
      - 9090:8080
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf

networks:
  rabbitmq_go_net_2:
    driver: bridge
